### ISSUE TITLE
vercel 部署报错

### ISSUE THREAD

**Issue by chuxinshuo** [izuolan/notionic#21]
主题，很喜欢，谢谢共享

一开始可以正好部署，前天开始突然报错了，回滚到之前正常的版本也报错，

不知道是Vercel 的问题，还是设置的问题，

还有一个问题，文章的cover图片怎么更改呢？只能调用默认cover图片吗？
![image](https://user-images.githubusercontent.com/50224473/233513105-3618c5d5-f106-4f02-bce6-39cafa394298.png)
![image](https://user-images.githubusercontent.com/50224473/233513148-e6762b4c-17c2-4a64-bbf0-574da6e2ddb3.png)

**Comment by izuolan** [comment]
哦, 我看了一下你的 notion 数据库, 这是因为你有两篇文章没有写 slug/date/status/type 这些信息(路径/发表日期/发布状态/发布类型), 你把它填上就可以了(应该).

![image](https://user-images.githubusercontent.com/5241553/233526236-2a7b48b7-2d32-452b-b056-37eff12d2fb9.png)

**Comment by chuxinshuo** [comment]
> 这

确实是这个问题，可以正常部署了，谢谢!


第二个问题可以解决吗？首页文章的 cover 图片...移动端都显示一样的不太美观

**Comment by izuolan** [comment]
哦, 抱歉忘记还有个 cover 的问题了.

cover 是自动读取 notion 页面封面的, 你可以在 notion 里设置每篇文章的封面, 如果没有设置才读取默认的那张图片(public/cover.jpg).

![image](https://user-images.githubusercontent.com/5241553/233534520-392bed6b-eecd-4e22-a91e-3687e156b908.png)

**Comment by chuxinshuo** [comment]
好的，谢谢解答疑惑
